FORMAT: 1A
HOST: https://blog.api.kinlane.com/

# Blog
This is an blog for all my blog entries. I use a single blog system to manage all my sites. Based upon tagging, I then publish each post out to its respective Github Page based repo.

## Authentication
This API uses Custom Query Parameter for its authentication.

The parameters that are needed to be sent for this type of authentication are as follows:
+ `appid`
+ `appkey`

# Group Blog

## Blog [/blog/{?appid,appkey,query,page,count,sort}]

### getBlogs [GET]
all blogs
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog

    + query (string, optional)

        a text query to search across blog

    + page (string, optional)

        which page of results to show

    + count (string, optional)

        how many to show on page

    + sort (string, optional)

        which field to sort by


+ Response 200 (application/json)
    + Attributes (array[blog])


## Blog [/blog/{?appid,appkey,title,author,summary,body,footer,status,curated_id}]

### addBlog [POST]
add a blog post
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog

    + title (string, required)

        ttle for the blog

    + author (string, optional)

        author of the blog

    + summary (string, optional)

        summary for the blog

    + body (string, optional)

        full text for the blog

    + footer (string, optional)

        curated id the blog originated from

    + status (string, optional)

        status of the blog

    + curated_id (number, optional)

        full text for the blog


+ Response 200 (application/json)
    + Attributes (array[blog])


## Blog Published [/blog/published/{?appid,appkey,page,count,sort}]

### getPublishedBlogs [GET]
published blogs
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog

    + page (string, optional)

        which page of results to show

    + count (string, optional)

        how many to show on page

    + sort (string, optional)

        which field to sort by


+ Response 200 (application/json)
    + Attributes (array[blog])


## Blog Draft [/blog/draft/{?appid,appkey,page,count,sort}]

### getDraftBlogs [GET]
draft blogs
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog

    + page (string, optional)

        which page of results to show

    + count (string, optional)

        how many to show on page

    + sort (string, optional)

        which field to sort by


+ Response 200 (application/json)
    + Attributes (array[blog])


## Blog By Blog Id [/blog/{blog_id}/{?appid,appkey}]

+ Parameters
    + blog_id (number, required)

        the unique id for blog entry


### getBlog [GET]
Returns the blog detail
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog


+ Response 200 (application/json)
    + Attributes (array[blog])


## Blog By Blog Id [/blog/{blog_id}/{?appid,appkey,post_date,title,author,summary,body,footer,status,build_page,github_build,twitter_build,linkedin_build,show_on_site}]

+ Parameters
    + blog_id (number, required)

        the unique id for blog entry


### updateBlog [PUT]
update blog
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog

    + post_date (string, optional)

        date the blog was posted

    + title (string, optional)

        ttle for the blog

    + author (string, optional)

        author of the blog

    + summary (string, optional)

        summary for the blog

    + body (string, optional)

        full text for the blog

    + footer (string, optional)

        curated id the blog originated from

    + status (string, optional)

        status of the blog

    + build_page (number, optional)

        whether or not this blog post needs page built

    + github_build (string, optional)

        the github build string

    + twitter_build (string, optional)

        the twitter build string

    + linkedin_build (string, optional)

        the linkedin build string

    + show_on_site (number, optional)

        Whether or not this blog post will show on any site


+ Response 200 (application/json)
    + Attributes (array[blog])


## Blog By Blog Id [/blog/{blog_id}/{?appid,appkey}]

+ Parameters
    + blog_id (number, required)

        the unique id for blog entry


### deleteBlog [DELETE]
delete blog
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog


+ Response 200 (application/json)
    + Attributes (array[blog])


## Blog Byweek [/blog/byweek/{?appid,appkey}]

### getBlogsByWeek [GET]
blogs by week
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog


+ Response 200 (application/json)
    + Attributes (array[blog])



# Group Tags

## Blog Tags By Blog Id [/blog/{blog_id}/tags/{?appid,appkey}]

+ Parameters
    + blog_id (number, required)

        id for blog


### getblogTags [GET]
blog tags
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog


+ Response 200 (application/json)
    + Attributes (array[tag])


## Blog Tags By Blog Id [/blog/{blog_id}/tags/{?appid,appkey,tag}]

+ Parameters
    + blog_id (number, required)

        id for the blog


### addBlogTag [POST]
add tag to blog
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog

    + tag (string, required)

        tag name


+ Response 200 (application/json)
    + Attributes (array[tag])


## Blog Tags By Blog Id And Tag [/blog/{blog_id}/tags/{tag}{?appid,appkey}]

+ Parameters
    + blog_id (string, required)

        id for the blog

    + tag (string, required)

        tag to remove from blog


### deleteblogTag [DELETE]
delete blog tag
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog


+ Response 200 (application/json)
    + Attributes (array[tag])


## Blog Tags Byweek [/blog/tags/byweek/{?appid,appkey,week,year}]

### getBlogTagsByWeek [GET]
blog tags by week
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog

    + week (string, required)

        the week to retrieve tags by

    + year (string, optional)

        the year to retrieve tags by


+ Response 200 (application/json)
    + Attributes (array[blog])


## Blog Tags Byweek Blog By Tag [/blog/tags/byweek/{tag}/blog/{?appid,appkey,week}]

+ Parameters
    + tag (string, required)

        the tag to filter by


### getBlogTagCBlog [GET]
blog tags by week blogs
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog

    + week (string, required)

        the week to filter by, defaults to this week


+ Response 200 (application/json)
    + Attributes (array[blog])


## Blog Tags Build By Tag [/blog/tags/{tag}/build/{?appid,appkey}]

+ Parameters
    + tag (string, required)

        the tag to filter by


### getBlogsToBuildByTag [GET]
build by tag
+ Parameters
    + appid (string, required)

        your appid for accessing the blog

    + appkey (string, required)

        your appkey for accessing the blog


+ Response 200 (application/json)
    + Attributes (array[blog])



# Data Structures

## blog (object)


### Properties
+ `blog_id` (number, optional) - unique id of the blog
+ `post_date` (string, optional) - date the blog was posted
+ `title` (string, optional) - ttle for the blog
+ `author` (string, optional) - author of the blog
+ `summary` (string, optional) - summary for the blog
+ `body` (string, optional) - full body text of the blog
+ `footer` (string, optional) - footer text for the blog
+ `status` (string, optional) - status of the blog
+ `curated_id` (number, optional) - curated id the blog originated from
+ `build_page` (number, optional) - Whether or not this blog post will show on any site
+ `show_on_site` (number, optional) - curated id the blog originated from


## tag (object)


### Properties
+ `tag_id` (number, optional) - id for the tag
+ `tag` (string, optional) - text tag
+ `api_count` (number, optional) - number of items api with tag
